# In this Docker Compose example, it assumes that you maintain a reverse proxy externally (or chose not to).
# The only two exposed ports here are from minio (:9000) and the app itself (:3000).
# If these ports are changed, ensure that the env vars passed to the app are also changed accordingly.

services:
  # Database (Postgres)
  postgres:
    image: ${REACTIVERESUMEDBIMAGE}
    restart: unless-stopped
    volumes:
      - ${REACTIVERESUMEDBDATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    image: minio/minio:${REACTIVERESUMEMINIIOVERSION}
    restart: unless-stopped
    command: server /data --address :"${MINIPORT}"
    ports:
      - "${MINIPORT}:${MINIPORT}"
    volumes:
      - ${REACTIVERESUMEMINIIODATA}:/data
    environment:
      MINIO_ROOT_USER: ${MINIADMIN}
      MINIO_ROOT_PASSWORD: ${MINIPASSWORD}


  # Chrome Browser (for printing and previews)
  chrome:
    image: ghcr.io/browserless/chromium:${REACTIVERESUMECHROMEVERSION} # Upgrading to newer versions causes issues
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TIMEOUT: 10000
      CONCURRENT: 10
      TOKEN: ${CHROMETOKEN}
      EXIT_ON_HEALTH_FAILURE: "true"
      PRE_REQUEST_HEALTH_CHECK: "true"

  app:
    image: amruthpillai/reactive-resume:${REACTIVERESUMEVERSION}
    restart: unless-stopped
    ports:
      - "${APPPORT}:${APPPORT}"
    depends_on:
      - postgres
      - minio
      - chrome
    environment:
      # -- Environment Variables --
      PORT: ${APPPORT}
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: ${REACTIVERESUMEURL}
      STORAGE_URL: http://${SERVERIP}:${MINIPORT}/default
      # -- Printer (Chrome) --
      CHROME_TOKEN: ${CHROMETOKEN}

      CHROME_URL: ws://chrome:${APPPORTOUT}

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_USER}:5432/${POSTGRES_DB}

      # -- Auth --
      ACCESS_TOKEN_SECRET: ${ACCESSTOKEN}
      REFRESH_TOKEN_SECRET: ${REFRESHTOKEN}

      # -- Emails --
      MAIL_FROM: ${REACTIVERESUMEEMAIL}
      SMTP_URL: ${SMTPURL} # Optional

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: ${STORAGEENDPOINT}
      STORAGE_PORT: ${MINIPORT}
      STORAGE_REGION: ${STORAGEREGION} # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: ${MINIADMIN}
      STORAGE_SECRET_KEY: ${MINIPASSWORD}
      STORAGE_USE_SSL: "false"
      STORAGE_SKIP_BUCKET_CHECK: "false"
      

      # -- Crowdin (Optional) --
      # CROWDIN_PROJECT_ID:
      # CROWDIN_PERSONAL_TOKEN:

      # -- Email (Optional) --
      DISABLE_SIGNUPS: "false"
      DISABLE_EMAIL_AUTH: "false"

      # -- GitHub (Optional) --
      # GITHUB_CLIENT_ID: github_client_id
      # GITHUB_CLIENT_SECRET: github_client_secret
      # GITHUB_CALLBACK_URL: http://localhost:${APPPORT/api/auth/github/callback

      # -- Google (Optional) --
      # GOOGLE_CLIENT_ID: google_client_id
      # GOOGLE_CLIENT_SECRET: google_client_secret
      # GOOGLE_CALLBACK_URL: http://localhost:${APPPORT/api/auth/google/callback

      # -- OpenID (Optional) --
      # VITE_OPENID_NAME: OpenID
      # OPENID_AUTHORIZATION_URL:
      # OPENID_CALLBACK_URL: http://localhost:${APPPORT/api/auth/openid/callback
      # OPENID_CLIENT_ID:
      # OPENID_CLIENT_SECRET:
      # OPENID_ISSUER:
      # OPENID_SCOPE: openid profile email
      # OPENID_TOKEN_URL:
      # OPENID_USER_INFO_URL:
