services:
  app:
    image: fireflyiii/core:${FIREFLYVERSION}
    hostname: ${HOSTNAME}
    container_name: ${FIREFLYCONTAINERNAME}
    restart: always
    volumes:
      - ${FIREFLYDATA}:/var/www/html/storage/upload
    env_file: .env
    networks:
      - ${FIREFLYNETWORK}
    ports:
      - ${PORTIN}:${PORTOUT}
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: ${FIREFLYDBHOSTNAME}
    container_name: ${FIREFLYDBCONTAINERNAME}
    restart: always
    env_file: .db.env
    networks:
      - ${FIREFLYNETWORK}
    volumes:
      - ${FIREFLYDBDATA}:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: ${FIREFLYCRONIMAGE}
    restart: always
    container_name: ${FIREFLYCRONCONTAINERNAME}
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      ln -fs /usr/share/zoneinfo/$$TZ /etc/localtime && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    networks:
      - firefly_iii
    depends_on:
      - app

  importer:
    image: fireflyiii/data-importer:${FIREFLYIMPORTERVERSION}
    hostname: importer
    restart: always
    container_name: ${FIREFLYIMPORTERCONTAINERNAME}
    networks:
      - ${FIREFLYNETWORK}
    ports:
      - '${BUDGETPORTIN}:${PORTOUT}'
    depends_on:
      - app
    env_file: .importer.env
#volumes:
#   firefly_iii_upload:
#   firefly_iii_db:

networks:
  firefly_iii:
    driver: ${FIREFLYNETWORKDRIVER}
