services:
  wishlist:
    container_name: wishlist
    image: ghcr.io/cmintey/wishlist:latest
    ports:
      - ${WISHLISTPORT}:${WISHLISTPORT}
    volumes:
      - ./uploads:/usr/src/app/uploads  # This is where user image uploads will be stored
      - ./data:/usr/src/app/data        # This is where the sqlite database will be stored
    environment:
      # ORIGIN: https://wishlist.example.com
      ORIGIN: ${WISHLISTURL} # The URL your users will be connecting to
      TOKEN_TIME: 1 # hours until signup and password reset tokens expire
