server:
  assets-path: ${GLANCEAPPASSETS}
  port: ${GLANCEPORT}

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: ${GLANCECSS}

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
#Uncomment this and run command from glance documents if you want a glance password
#auth:
  #secret-key: ${GLANCESECRETKEY}
  #users:
    #${GLANCEADMINUSERNAME}:
      #password: ${GLANCEADMINPASSWORD}
